# (base_name, ClassName, uses_output_flag)  — pipeline tools only (no pview/pstats/text-stats/benchmarks)
TOOLS = [
    ("egg2bam","Egg2Bam",True), ("bam2egg","Bam2Egg",True), ("bam-info","BamInfo",False),
    ("pzip","Pzip",False), ("punzip","Punzip",False), ("multify","Multify",False),
    ("egg-trans","EggTrans",True), ("egg-crop","EggCrop",True), ("egg-optchar","EggOptchar",True),
    ("egg-palettize","EggPalettize",True), ("egg-qtess","EggQtess",True), ("egg-rename","EggRename",True),
    ("egg-retarget-anim","EggRetargetAnim",True), ("egg-texture-cards","EggTextureCards",True),
    ("egg-topstrip","EggTopstrip",True), ("egg-make-tube","EggMakeTube",True),
    ("egg-list-textures","EggListTextures",False), ("egg-mkfont","EggMkfont",True),
    ("egg2flt","Egg2Flt",True), ("flt2egg","Flt2Egg",True), ("flt-info","FltInfo",False), ("flt-trans","FltTrans",True),
    ("egg2obj","Egg2Obj",True), ("obj2egg","Obj2Egg",True),
    ("egg2dxf","Egg2Dxf",True), ("dxf2egg","Dxf2Egg",True), ("dxf-points","DxfPoints",False),
    ("egg2x","Egg2X",True), ("x2egg","X2Egg",True), ("x-trans","XTrans",True),
    ("vrml2egg","Vrml2Egg",True), ("vrml-trans","VrmlTrans",True),
    ("lwo2egg","Lwo2Egg",True), ("lwo-scan","LwoScan",False),
    ("image-trans","ImageTrans",True), ("image-resize","ImageResize",True), ("image-info","ImageInfo",False),
    ("image-fix-hidden-color","ImageFixHiddenColor",True), ("image-transform-colors","ImageTransformColors",True),
    ("pfm-trans","PfmTrans",True), ("pfm-bba","PfmBba",True),
    ("pts2bam","Pts2Bam",False), ("pdecrypt","Pdecrypt",False), ("pencrypt","Pencrypt",False),
    ("txo-converter","TxoConverter",True), ("p3dcparse","P3dcparse",True),
    ("bin2c","Bin2C",True), ("egg2c","Egg2C",True),
]

# ---- PipelineTasks.cs ----
cs = ['// <auto-generated> One thin ToolTask per pipeline executable in Panda3D.Tools.',
      '// Regenerate with csharp/Panda3D.Tools.Tasks/gen_tasks.py. </auto-generated>',
      '', 'namespace Panda3D.Tools.Tasks', '{']
for base, cls, uo in TOOLS:
    cs.append(f'    /// <summary>MSBuild task wrapping the Panda3D <c>{base}</c> tool.</summary>')
    cs.append(f'    public sealed class {cls} : PandaToolTask')
    cs.append('    {')
    cs.append(f'        protected override string ToolBaseName => "{base}";')
    if not uo:
        cs.append('        protected override bool UsesOutputFlag => false;')
    cs.append('    }')
    cs.append('')
cs.append('}')
open('/home/maxwell/CLionProjects/panda3d/csharp/Panda3D.Tools.Tasks/PipelineTasks.cs','w').write('\n'.join(cs)+'\n')

# ---- UsingTask fragment for the .targets ----
ut = ['  <!-- Register one MSBuild task per pipeline tool (auto-generated list). -->',
      '  <ItemGroup />']
lines = []
for base, cls, uo in TOOLS:
    lines.append(f'  <UsingTask TaskName="Panda3D.Tools.Tasks.{cls}" AssemblyFile="$(_P3TasksDll)" Condition="Exists(\'$(_P3TasksDll)\')" />')
open('/tmp/usingtasks.xml','w').write('\n'.join(lines)+'\n')
print(f"generated {len(TOOLS)} tasks")
