// <auto-generated> One thin ToolTask per pipeline executable in Panda3D.Tools.
// Regenerate with csharp/Panda3D.Tools.Tasks/gen_tasks.py. </auto-generated>

namespace Panda3D.Tools.Tasks
{
    /// <summary>MSBuild task wrapping the Panda3D <c>egg2bam</c> tool.</summary>
    public sealed class Egg2Bam : PandaToolTask
    {
        protected override string ToolBaseName => "egg2bam";
    }

    /// <summary>MSBuild task wrapping the Panda3D <c>bam2egg</c> tool.</summary>
    public sealed class Bam2Egg : PandaToolTask
    {
        protected override string ToolBaseName => "bam2egg";
    }

    /// <summary>MSBuild task wrapping the Panda3D <c>bam-info</c> tool.</summary>
    public sealed class BamInfo : PandaToolTask
    {
        protected override string ToolBaseName => "bam-info";
        protected override bool UsesOutputFlag => false;
    }

    /// <summary>MSBuild task wrapping the Panda3D <c>pzip</c> tool.</summary>
    public sealed class Pzip : PandaToolTask
    {
        protected override string ToolBaseName => "pzip";
        protected override bool UsesOutputFlag => false;
    }

    /// <summary>MSBuild task wrapping the Panda3D <c>punzip</c> tool.</summary>
    public sealed class Punzip : PandaToolTask
    {
        protected override string ToolBaseName => "punzip";
        protected override bool UsesOutputFlag => false;
    }

    /// <summary>MSBuild task wrapping the Panda3D <c>multify</c> tool.</summary>
    public sealed class Multify : PandaToolTask
    {
        protected override string ToolBaseName => "multify";
        protected override bool UsesOutputFlag => false;
    }

    /// <summary>MSBuild task wrapping the Panda3D <c>egg-trans</c> tool.</summary>
    public sealed class EggTrans : PandaToolTask
    {
        protected override string ToolBaseName => "egg-trans";
    }

    /// <summary>MSBuild task wrapping the Panda3D <c>egg-crop</c> tool.</summary>
    public sealed class EggCrop : PandaToolTask
    {
        protected override string ToolBaseName => "egg-crop";
    }

    /// <summary>MSBuild task wrapping the Panda3D <c>egg-optchar</c> tool.</summary>
    public sealed class EggOptchar : PandaToolTask
    {
        protected override string ToolBaseName => "egg-optchar";
    }

    /// <summary>MSBuild task wrapping the Panda3D <c>egg-palettize</c> tool.</summary>
    public sealed class EggPalettize : PandaToolTask
    {
        protected override string ToolBaseName => "egg-palettize";
    }

    /// <summary>MSBuild task wrapping the Panda3D <c>egg-qtess</c> tool.</summary>
    public sealed class EggQtess : PandaToolTask
    {
        protected override string ToolBaseName => "egg-qtess";
    }

    /// <summary>MSBuild task wrapping the Panda3D <c>egg-rename</c> tool.</summary>
    public sealed class EggRename : PandaToolTask
    {
        protected override string ToolBaseName => "egg-rename";
    }

    /// <summary>MSBuild task wrapping the Panda3D <c>egg-retarget-anim</c> tool.</summary>
    public sealed class EggRetargetAnim : PandaToolTask
    {
        protected override string ToolBaseName => "egg-retarget-anim";
    }

    /// <summary>MSBuild task wrapping the Panda3D <c>egg-texture-cards</c> tool.</summary>
    public sealed class EggTextureCards : PandaToolTask
    {
        protected override string ToolBaseName => "egg-texture-cards";
    }

    /// <summary>MSBuild task wrapping the Panda3D <c>egg-topstrip</c> tool.</summary>
    public sealed class EggTopstrip : PandaToolTask
    {
        protected override string ToolBaseName => "egg-topstrip";
    }

    /// <summary>MSBuild task wrapping the Panda3D <c>egg-make-tube</c> tool.</summary>
    public sealed class EggMakeTube : PandaToolTask
    {
        protected override string ToolBaseName => "egg-make-tube";
    }

    /// <summary>MSBuild task wrapping the Panda3D <c>egg-list-textures</c> tool.</summary>
    public sealed class EggListTextures : PandaToolTask
    {
        protected override string ToolBaseName => "egg-list-textures";
        protected override bool UsesOutputFlag => false;
    }

    /// <summary>MSBuild task wrapping the Panda3D <c>egg-mkfont</c> tool.</summary>
    public sealed class EggMkfont : PandaToolTask
    {
        protected override string ToolBaseName => "egg-mkfont";
    }

    /// <summary>MSBuild task wrapping the Panda3D <c>egg2flt</c> tool.</summary>
    public sealed class Egg2Flt : PandaToolTask
    {
        protected override string ToolBaseName => "egg2flt";
    }

    /// <summary>MSBuild task wrapping the Panda3D <c>flt2egg</c> tool.</summary>
    public sealed class Flt2Egg : PandaToolTask
    {
        protected override string ToolBaseName => "flt2egg";
    }

    /// <summary>MSBuild task wrapping the Panda3D <c>flt-info</c> tool.</summary>
    public sealed class FltInfo : PandaToolTask
    {
        protected override string ToolBaseName => "flt-info";
        protected override bool UsesOutputFlag => false;
    }

    /// <summary>MSBuild task wrapping the Panda3D <c>flt-trans</c> tool.</summary>
    public sealed class FltTrans : PandaToolTask
    {
        protected override string ToolBaseName => "flt-trans";
    }

    /// <summary>MSBuild task wrapping the Panda3D <c>egg2obj</c> tool.</summary>
    public sealed class Egg2Obj : PandaToolTask
    {
        protected override string ToolBaseName => "egg2obj";
    }

    /// <summary>MSBuild task wrapping the Panda3D <c>obj2egg</c> tool.</summary>
    public sealed class Obj2Egg : PandaToolTask
    {
        protected override string ToolBaseName => "obj2egg";
    }

    /// <summary>MSBuild task wrapping the Panda3D <c>egg2dxf</c> tool.</summary>
    public sealed class Egg2Dxf : PandaToolTask
    {
        protected override string ToolBaseName => "egg2dxf";
    }

    /// <summary>MSBuild task wrapping the Panda3D <c>dxf2egg</c> tool.</summary>
    public sealed class Dxf2Egg : PandaToolTask
    {
        protected override string ToolBaseName => "dxf2egg";
    }

    /// <summary>MSBuild task wrapping the Panda3D <c>dxf-points</c> tool.</summary>
    public sealed class DxfPoints : PandaToolTask
    {
        protected override string ToolBaseName => "dxf-points";
        protected override bool UsesOutputFlag => false;
    }

    /// <summary>MSBuild task wrapping the Panda3D <c>egg2x</c> tool.</summary>
    public sealed class Egg2X : PandaToolTask
    {
        protected override string ToolBaseName => "egg2x";
    }

    /// <summary>MSBuild task wrapping the Panda3D <c>x2egg</c> tool.</summary>
    public sealed class X2Egg : PandaToolTask
    {
        protected override string ToolBaseName => "x2egg";
    }

    /// <summary>MSBuild task wrapping the Panda3D <c>x-trans</c> tool.</summary>
    public sealed class XTrans : PandaToolTask
    {
        protected override string ToolBaseName => "x-trans";
    }

    /// <summary>MSBuild task wrapping the Panda3D <c>vrml2egg</c> tool.</summary>
    public sealed class Vrml2Egg : PandaToolTask
    {
        protected override string ToolBaseName => "vrml2egg";
    }

    /// <summary>MSBuild task wrapping the Panda3D <c>vrml-trans</c> tool.</summary>
    public sealed class VrmlTrans : PandaToolTask
    {
        protected override string ToolBaseName => "vrml-trans";
    }

    /// <summary>MSBuild task wrapping the Panda3D <c>lwo2egg</c> tool.</summary>
    public sealed class Lwo2Egg : PandaToolTask
    {
        protected override string ToolBaseName => "lwo2egg";
    }

    /// <summary>MSBuild task wrapping the Panda3D <c>lwo-scan</c> tool.</summary>
    public sealed class LwoScan : PandaToolTask
    {
        protected override string ToolBaseName => "lwo-scan";
        protected override bool UsesOutputFlag => false;
    }

    /// <summary>MSBuild task wrapping the Panda3D <c>image-trans</c> tool.</summary>
    public sealed class ImageTrans : PandaToolTask
    {
        protected override string ToolBaseName => "image-trans";
    }

    /// <summary>MSBuild task wrapping the Panda3D <c>image-resize</c> tool.</summary>
    public sealed class ImageResize : PandaToolTask
    {
        protected override string ToolBaseName => "image-resize";
    }

    /// <summary>MSBuild task wrapping the Panda3D <c>image-info</c> tool.</summary>
    public sealed class ImageInfo : PandaToolTask
    {
        protected override string ToolBaseName => "image-info";
        protected override bool UsesOutputFlag => false;
    }

    /// <summary>MSBuild task wrapping the Panda3D <c>image-fix-hidden-color</c> tool.</summary>
    public sealed class ImageFixHiddenColor : PandaToolTask
    {
        protected override string ToolBaseName => "image-fix-hidden-color";
    }

    /// <summary>MSBuild task wrapping the Panda3D <c>image-transform-colors</c> tool.</summary>
    public sealed class ImageTransformColors : PandaToolTask
    {
        protected override string ToolBaseName => "image-transform-colors";
    }

    /// <summary>MSBuild task wrapping the Panda3D <c>pfm-trans</c> tool.</summary>
    public sealed class PfmTrans : PandaToolTask
    {
        protected override string ToolBaseName => "pfm-trans";
    }

    /// <summary>MSBuild task wrapping the Panda3D <c>pfm-bba</c> tool.</summary>
    public sealed class PfmBba : PandaToolTask
    {
        protected override string ToolBaseName => "pfm-bba";
    }

    /// <summary>MSBuild task wrapping the Panda3D <c>pts2bam</c> tool.</summary>
    public sealed class Pts2Bam : PandaToolTask
    {
        protected override string ToolBaseName => "pts2bam";
        protected override bool UsesOutputFlag => false;
    }

    /// <summary>MSBuild task wrapping the Panda3D <c>pdecrypt</c> tool.</summary>
    public sealed class Pdecrypt : PandaToolTask
    {
        protected override string ToolBaseName => "pdecrypt";
        protected override bool UsesOutputFlag => false;
    }

    /// <summary>MSBuild task wrapping the Panda3D <c>pencrypt</c> tool.</summary>
    public sealed class Pencrypt : PandaToolTask
    {
        protected override string ToolBaseName => "pencrypt";
        protected override bool UsesOutputFlag => false;
    }

    /// <summary>MSBuild task wrapping the Panda3D <c>txo-converter</c> tool.</summary>
    public sealed class TxoConverter : PandaToolTask
    {
        protected override string ToolBaseName => "txo-converter";
    }

    /// <summary>MSBuild task wrapping the Panda3D <c>p3dcparse</c> tool.</summary>
    public sealed class P3dcparse : PandaToolTask
    {
        protected override string ToolBaseName => "p3dcparse";
    }

    /// <summary>MSBuild task wrapping the Panda3D <c>bin2c</c> tool.</summary>
    public sealed class Bin2C : PandaToolTask
    {
        protected override string ToolBaseName => "bin2c";
    }

    /// <summary>MSBuild task wrapping the Panda3D <c>egg2c</c> tool.</summary>
    public sealed class Egg2C : PandaToolTask
    {
        protected override string ToolBaseName => "egg2c";
    }

}
