#nullable enable

using System;
using System.IO;

namespace Panda3D.Core;

// byte[] <-> the generated byte collections.

public partial class vector_uchar {
  // A byte[] overload is required: without it new vector_uchar(bytes) is ambiguous
  // between the ReadOnlySpan<byte> and IEnumerable<byte> constructors (CS0121).
  /// <summary>Copies <paramref name="source"/> into a new native byte vector.</summary>
  public vector_uchar(byte[] source)
    : this(new ReadOnlySpan<byte>(source ?? throw new ArgumentNullException(nameof(source)))) {
  }

  /// <summary>Copies the bytes into a new native vector.</summary>
  public static implicit operator vector_uchar(byte[] source) => new(source);

  /// <summary>Copies the bytes into a new native vector.</summary>
  public static implicit operator vector_uchar(ReadOnlySpan<byte> source) => new(source);

  /// <summary>Copies the contents out to a managed array. Explicit: it copies.</summary>
  public static explicit operator byte[](vector_uchar value) {
    ArgumentNullException.ThrowIfNull(value);
    return value.ToArray();
  }

  /// <summary>Writes the contents straight from native memory to a stream.</summary>
  public void WriteTo(Stream destination) {
    ArgumentNullException.ThrowIfNull(destination);
    destination.Write(AsReadOnlySpan());
  }

  /// <summary>Reads <paramref name="source"/> to its end into a new native vector.</summary>
  public static vector_uchar FromStream(Stream source) {
    ArgumentNullException.ThrowIfNull(source);
    using var buffer = new MemoryStream();
    source.CopyTo(buffer);
    if (buffer.TryGetBuffer(out ArraySegment<byte> segment) && segment.Array is not null) {
      return new vector_uchar(new ReadOnlySpan<byte>(segment.Array, segment.Offset, segment.Count));
    }
    return new vector_uchar(buffer.ToArray());
  }
}

public partial class vector_uchar_const {
  /// <summary>Copies the contents out to a managed array. Explicit: it copies.</summary>
  public static explicit operator byte[](vector_uchar_const value) {
    ArgumentNullException.ThrowIfNull(value);
    return value.ToArray();
  }

  /// <summary>Writes the contents straight from native memory to a stream.</summary>
  public void WriteTo(Stream destination) {
    ArgumentNullException.ThrowIfNull(destination);
    destination.Write(AsReadOnlySpan());
  }
}

// PTA_uchar / CPTA_uchar have no span or bulk copy (they are driven through the
// type's own published accessors), so these go element-wise.

public partial class PTA_uchar {
  /// <summary>Copies the contents out to a managed array.</summary>
  public byte[] ToArray() {
    var result = new byte[Count];
    CopyTo(result, 0);
    return result;
  }

  /// <summary>Copies <paramref name="source"/> into a new reference-counted array.</summary>
  public static PTA_uchar From(ReadOnlySpan<byte> source) {
    var result = new PTA_uchar();
    foreach (byte b in source) {
      result.Add(b);
    }
    return result;
  }

  /// <summary>Copies the bytes into a new reference-counted array.</summary>
  public static implicit operator PTA_uchar(byte[] source) {
    ArgumentNullException.ThrowIfNull(source);
    return From(source);
  }

  /// <summary>Copies the contents out to a managed array. Explicit: it copies.</summary>
  public static explicit operator byte[](PTA_uchar value) {
    ArgumentNullException.ThrowIfNull(value);
    return value.ToArray();
  }

  /// <summary>Writes the contents to a stream.</summary>
  public void WriteTo(Stream destination) {
    ArgumentNullException.ThrowIfNull(destination);
    destination.Write(ToArray());
  }
}

public partial class CPTA_uchar {
  /// <summary>Copies the contents out to a managed array.</summary>
  public byte[] ToArray() {
    var result = new byte[Count];
    for (int i = 0; i < result.Length; ++i) {
      result[i] = this[i];
    }
    return result;
  }

  /// <summary>Copies the contents out to a managed array. Explicit: it copies.</summary>
  public static explicit operator byte[](CPTA_uchar value) {
    ArgumentNullException.ThrowIfNull(value);
    return value.ToArray();
  }

  /// <summary>Copies <paramref name="source"/> into a new const reference-counted array.</summary>
  public static CPTA_uchar From(ReadOnlySpan<byte> source) => new(PTA_uchar.From(source));

  /// <summary>Copies the bytes into a new const reference-counted array. Enables passing a
  /// <c>byte[]</c> straight to any API taking a CPTA_uchar (e.g. Texture.SetRamImage).</summary>
  public static implicit operator CPTA_uchar(byte[] source) {
    ArgumentNullException.ThrowIfNull(source);
    return new CPTA_uchar(PTA_uchar.From(source));
  }

  /// <summary>Copies the bytes into a new const reference-counted array.</summary>
  public static implicit operator CPTA_uchar(ReadOnlySpan<byte> source) => new(PTA_uchar.From(source));

  /// <summary>Writes the contents to a stream.</summary>
  public void WriteTo(Stream destination) {
    ArgumentNullException.ThrowIfNull(destination);
    destination.Write(ToArray());
  }
}
