if(NOT BUILD_TOOLS)
  return()
endif()

add_executable(pview pview.cxx)
target_link_libraries(pview p3framework)
install(TARGETS pview EXPORT Tools COMPONENT Tools DESTINATION ${CMAKE_INSTALL_BINDIR})

if(NOT BUILD_SHARED_LIBS)
  if(HAVE_GL)
    target_link_libraries(pview pandagl)
  endif()
  if(HAVE_DX9)
    target_link_libraries(pview pandadx9)
  endif()
  if(HAVE_TINYDISPLAY)
    target_link_libraries(pview p3tinydisplay)
  endif()
endif()
